# Generated by Django 3.2.7 on 2021-11-10 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_scheduler', '0004_rename_is_staff_userprofile_is_vaccinated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='is_vaccinated',
            new_name='is_staff',
        ),
    ]
