# Generated by Django 3.2.7 on 2021-11-16 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_scheduler', '0006_auto_20211113_1859'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='is_staff',
            new_name='is_vaccinated',
        ),
    ]
