# Generated by Django 3.2.7 on 2021-11-19 21:26

from django.db import migrations, models
import event_scheduler.utils


class Migration(migrations.Migration):

    dependencies = [
        ('event_scheduler', '0011_auto_20211118_2243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingitem',
            name='Room_number',
        ),
        migrations.RemoveField(
            model_name='meetingroom',
            name='room_id',
        ),
        migrations.AddField(
            model_name='meetingroom',
            name='Availability',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='meetingroom',
            name='Floor',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meetingroom',
            name='Room_Types',
            field=models.CharField(choices=[('DESK ', 'DESK'), ('CONFRENCE ROOM', 'CONFRENCE')], default='CONFRENCE ROOM', max_length=14),
        ),
        migrations.AddField(
            model_name='meetingroom',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bookingitem',
            name='Booking_id',
            field=models.CharField(default=event_scheduler.utils.create_new_ref_number, max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
