# Generated by Django 3.2.7 on 2021-11-22 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_scheduler', '0016_auto_20211121_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingroom',
            name='Floor',
            field=models.CharField(max_length=2, unique=True),
        ),
    ]
