# Generated by Django 3.2.7 on 2021-11-22 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event_scheduler', '0017_alter_meetingroom_floor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingitem',
            name='Room_number',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room2room', to='event_scheduler.meetingroom'),
        ),
    ]
