# Generated by Django 3.2.7 on 2021-11-23 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event_scheduler', '0023_auto_20211122_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingitem',
            name='Duration',
            field=models.IntegerField(default=1),
        ),
    ]
