# Generated by Django 3.2.7 on 2021-11-25 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event_scheduler', '0026_auto_20211124_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingitem',
            name='Date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='bookingitem',
            name='Room_number',
            field=models.OneToOneField(default=101, on_delete=django.db.models.deletion.CASCADE, related_name='Room', to='event_scheduler.meetingroom', to_field='Room_number'),
            preserve_default=False,
        ),
    ]
