# Generated by Django 3.2.7 on 2021-11-25 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_scheduler', '0027_auto_20211125_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingitem',
            name='Date',
            field=models.DateField(verbose_name='Date'),
        ),
    ]
