# Generated by Django 3.2.7 on 2021-11-10 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_scheduler', '0003_rename_email_id_userprofile_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='is_staff',
            new_name='is_vaccinated',
        ),
    ]
