# Generated by Django 3.2.7 on 2021-11-19 00:27

from django.db import migrations, models
import django.db.models.deletion
import event_scheduler.utils


class Migration(migrations.Migration):

    dependencies = [
        ('event_scheduler', '0008_userprofile_is_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingRoom',
            fields=[
                ('room_id', models.CharField(blank=True, default=event_scheduler.utils.create_new_ref_number, editable=False, max_length=5, primary_key=True, serialize=False, unique=True)),
                ('room_number', models.CharField(max_length=16, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='bookingitem',
            name='status',
            field=models.IntegerField(choices=[(0, 'Valid'), (1, 'Cancelled')], default=0),
        ),
        migrations.AlterField(
            model_name='bookingitem',
            name='Booking_id',
            field=models.CharField(blank=True, default=event_scheduler.utils.create_new_ref_number, editable=False, max_length=10, primary_key=True, serialize=False, unique=True),
        )
    ]
