# Generated by Django 3.2.7 on 2021-11-19 00:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event_scheduler', '0009_auto_20211118_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingitem',
            name='room',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='event_scheduler.meetingroom'),
            preserve_default=False,
        ),
    ]
