# Generated by Django 3.2.7 on 2021-11-19 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_scheduler', '0010_bookingitem_room'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookingitem',
            old_name='room',
            new_name='Room_number',
        ),
        migrations.RemoveField(
            model_name='meetingroom',
            name='room_number',
        ),
        migrations.AddField(
            model_name='meetingroom',
            name='Room_number',
            field=models.CharField(default=1, max_length=5, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meetingroom',
            name='capacity',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
    ]
