# Generated by Django 3.2.7 on 2021-11-22 06:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event_scheduler', '0018_alter_bookingitem_room_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingitem',
            name='Floor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Floor2', to='event_scheduler.meetingroom'),
        ),
        migrations.AlterField(
            model_name='bookingitem',
            name='Room_number',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Room_number2', to='event_scheduler.meetingroom'),
        ),
        migrations.AlterField(
            model_name='bookingitem',
            name='User_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='User_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='ResetPasswordToken',
        ),
    ]
