# Generated by Django 3.2.7 on 2021-11-22 19:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event_scheduler', '0021_alter_bookingitem_user_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingitem',
            name='Floor',
        ),
        migrations.RemoveField(
            model_name='bookingitem',
            name='Room_number',
        ),
        migrations.AlterField(
            model_name='bookingitem',
            name='User_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='User_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
