# Generated by Django 3.2.7 on 2021-11-22 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event_scheduler', '0022_auto_20211122_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingitem',
            name='Room_number',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Room', to='event_scheduler.meetingroom', to_field='Room_number'),
        ),
    ]
