# Generated by Django 3.2.7 on 2021-12-04 02:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event_scheduler', '0028_alter_bookingitem_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_date', models.DateField(verbose_name='Date')),
                ('available_time_id', models.IntegerField(choices=[(1, '8:00'), (2, '9:00'), (3, '10:00'), (4, '11:00'), (5, '12:00'), (6, '13:00'), (7, '14:00'), (8, '15:00'), (9, '16:00'), (10, '17:00'), (11, '18:00'), (12, '19:00'), (13, '20:00')])),
                ('Room_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Roomavailbility', to='event_scheduler.meetingroom', to_field='Room_number')),
            ],
        ),
    ]
